apiVersion: skaffold/v1
kind: Config
metadata:
  name: migrations-db
deploy:
  kubectl:
    manifests:
      - k8s/migrations-db.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/migrations-db
  local: {}
